ALTER TABLE IF EXISTS public.denizbank_book ADD COLUMN IF NOT EXISTS is_invoiced BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.denizbank_pos_book ADD COLUMN IF NOT EXISTS is_invoiced BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.vakifbank_book ADD COLUMN IF NOT EXISTS is_invoiced BOOLEAN DEFAULT FALSE;
